MarketArea/MarketArea/Controllers/AdController.cs
using MarketArea.Contracts;
using MarketArea.Data.ModelDb;
using MarketArea.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;
using MarketArea.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MarketArea.Controllers
{
    public class AdController : BaseController
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly IAdService adService;
        private readonly IRepository repo;
        public AdController(UserManager<IdentityUser> _userManager, IAdService _adService, IRepository _repo)
        {
            userManager = _userManager;
            adService = _adService;
            repo = _repo;
        }

        public IActionResult Create()
        {
            var categories = repo.All<Category>().OrderBy(x => x.Name);
            var cities = repo.All<City>().OrderBy(x => x.Name);

            List<SelectListItem> itemsCategories = DropDownCategoriesMenu(categories);
            List<SelectListItem> itemsCities = DropDownCitiesMenu(cities);

            ViewBag.AdCategory = itemsCategories;
            ViewBag.AdCity = itemsCities;
            return View();
        }

        public IActionResult All(string category)
        {
            var user = userManager.GetUserAsync(User).Result;
            FavouritesViewModel favouritesViewModel = adService.all(category, user);
            var watch = new System.Diagnostics.Stopwatch();

            watch.Start();

            for (int i = 0; i < 1000; i++)
            {
                Console.Write(i);
            }

            watch.Stop();
            Console.WriteLine($"Execution Time: {watch.ElapsedMilliseconds} ms");
            return View(favouritesViewModel);
        }

        public IActionResult Details(string id)
        {
            var user = userManager.GetUserAsync(User).Result;
            LikeAdViewModel ad = adService.Details(id, user);

            return View(ad);
        }

        public IActionResult Edit(string id)
        {
            var ad = repo.All<Ad>().Include(c => c.Category).Include(c => c.City).FirstOrDefault(x => x.Id == id);
            if (ad == null)
            {
                return NotFound();
            }
            var categories = repo.All<Category>().OrderBy(x => x.Name);
            var cities = repo.All<City>().OrderBy(x => x.Name);

            List<SelectListItem> itemsCategories = DropDownCategoriesMenu(categories);
            itemsCategories.Single(x => x.Text == ad.Category.Name).Selected = true;

            List<SelectListItem> itemsCities = DropDownCitiesMenu(cities);
            itemsCities.Single(x => x.Text == ad.City.Name).Selected = true; ;

            ViewBag.AdCategory = itemsCategories;
            ViewBag.AdCity = itemsCities;
            


            return View(new EditViewModel()
            {
                Id = ad.Id,
                Name = ad.Name,
                ImageUrl = ad.ImageUrl,
                PhoneNumber = ad.PhoneNumber,
                Price = ad.Price,
                Description = ad.Description,

            });
        }

        [HttpPost]
        public IActionResult Create(CreateAdViewModel model)
        {
            var user = userManager.GetUserAsync(User).Result;
            var (created, error) = adService.Create(model, user);
            if (!created)
            {
                ModelState.AddModelError("",error);
                return View();
                //return Redirect("/Ad/Create");
            }

            return Redirect("/");
        }

        [HttpPost]
        public IActionResult Edit(EditViewModel model)
        {
            adService.Edit(model);
            
            return Redirect($"/Ad/Details/{model.Id}");

        }

        public IActionResult Delete(string id)
        {
            var removed = adService.Delete(id);
            if (!removed)
            {
                return Redirect($"/Ad/Details/{id}");
            }
            return Redirect("/");
        }


        private static List<SelectListItem> DropDownCategoriesMenu(IOrderedQueryable<Category> categories)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var category in categories)
            {
                items.Add(new SelectListItem { Text = category.Name });
            }

            return items;
        }
        private static List<SelectListItem> DropDownCitiesMenu(IOrderedQueryable<City> cities)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var city in cities)
            {
                items.Add(new SelectListItem { Text = city.Name });
            }

            return items;
        }

    }
}

MarketArea/MarketArea/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace MarketArea.Controllers
{
    public class ContactController : BaseController
    {
        public IActionResult Connection()
        {
            return View();
        }
    }
}

MarketArea/MarketArea/Controllers/FavoriteController.cs
using MarketArea.Contracts;
using MarketArea.Data.Common;
using MarketArea.Data.ModelDb;
using MarketArea.ViewModels;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MarketArea.Controllers
{
    public class FavoriteController : BaseController
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly IRepository repo;
        private readonly IFavoriteService favoriteService;

        public FavoriteController(UserManager<IdentityUser> _userManager, IRepository _repo, IFavoriteService _favoriteService)
        {
            userManager = _userManager;
            repo = _repo;
            favoriteService = _favoriteService;
        }

        public IActionResult MyFavorite()
        {
            var user = userManager.GetUserAsync(User).Result;
            FavouritesViewModel favouritesViewModel = favoriteService.MyFavorite(user);

            return View("Views/Ad/All.cshtml", favouritesViewModel);

        }

        [HttpPost]
        public IActionResult AddToFavorite(string id)
        {
            var user = userManager.GetUserAsync(User).Result;
            var message = favoriteService.Add(id, user);

            return Json(new { result = message });
        }

        public IActionResult RemoveFromFavorite(string id)
        {
            
            var user = userManager.GetUserAsync(User).Result;

            var isRemoved = favoriteService.Delete(id, user);
            if (!isRemoved)
            {
                Console.WriteLine("Cannot be removed");
            }

            return Json(new { result = "success"});
        }
    }
}

MarketArea/MarketArea/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarketArea</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MarketArea.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome-free/css/all.min.css" />
    <link rel="stylesheet" href="~/css/sidebar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/favoriteCheck.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div id="mySidebar" class="sidebar">
                <a href="javascript:void(0)" title="close" class="closebtn" onclick="closeNav()">&times;</a>
                <div>
                    <form class="search-form" role="search">
                        <div class="form-group md-form mt-0 pt-1 waves-light">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                    </form>
                </div>
                @await Component.InvokeAsync("Categories")
            </div>
            <div id="main">
                <button class="openbtn" onclick="openNav()">&#9776;</button>
            </div>

            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MarketArea</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ad" asp-action="Create">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Favorite" asp-action="MyFavorite">MyFavorite</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MarketArea - <a asp-area="" asp-controller="Contact" asp-action="Connection">Contact us</a>
            <a href="https://github.com/APeev89/MarketArea"><i class="fab fa-github" style='font-size:20px;color:black'></i></a>
            <a href="https://www.linkedin.com/in/apostol-peev-bb4913103/"><i class="fab fa-linkedin" style='font-size:20px;color:blue'></i></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sidebar.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>