MarketArea/MarketArea/ViewModels/EditViewModel.cs
using MarketArea.Data.ModelDb;

namespace MarketArea.ViewModels
{
    public class EditViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public decimal Price { get; set; }
        public string PhoneNumber { get; set; }
        public string Description { get; set; }
        public string AdCity { get; set; }
        public string AdCategory { get; set; }
    }
}

MarketArea/MarketArea/Controllers/AdController.cs
using MarketArea.Contracts;
using MarketArea.Data.ModelDb;
using MarketArea.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;
using MarketArea.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MarketArea.Controllers
{
    public class AdController : BaseController
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly IAdService adService;
        private readonly IRepository repo;
        public AdController(UserManager<IdentityUser> _userManager, IAdService _adService, IRepository _repo)
        {
            userManager = _userManager;
            adService = _adService;
            repo = _repo;
        }

        public IActionResult Create()
        {
            var categories = repo.All<Category>().OrderBy(x => x.Name);
            var cities = repo.All<City>().OrderBy(x => x.Name);

            List<SelectListItem> itemsCategories = DropDownCategoriesMenu(categories);
            List<SelectListItem> itemsCities = DropDownCitiesMenu(cities);

            ViewBag.AdCategory = itemsCategories;
            ViewBag.AdCity = itemsCities;
            return View();
        }

        public IActionResult All(string category)
        {
            var user = userManager.GetUserAsync(User).Result;
            FavouritesViewModel favouritesViewModel = adService.all(category, user);
            var watch = new System.Diagnostics.Stopwatch();

            watch.Start();

            for (int i = 0; i < 1000; i++)
            {
                Console.Write(i);
            }

            watch.Stop();
            Console.WriteLine($"Execution Time: {watch.ElapsedMilliseconds} ms");
            return View(favouritesViewModel);
        }

        public IActionResult Details(string id)
        {
            var user = userManager.GetUserAsync(User).Result;
            LikeAdViewModel ad = adService.Details(id, user);

            return View(ad);
        }

        public IActionResult Edit(string id)
        {
            var ad = repo.All<Ad>().Include(c => c.Category).Include(c => c.City).FirstOrDefault(x => x.Id == id);
            if (ad == null)
            {
                return NotFound();
            }
            var categories = repo.All<Category>().OrderBy(x => x.Name);
            var cities = repo.All<City>().OrderBy(x => x.Name);

            List<SelectListItem> itemsCategories = DropDownCategoriesMenu(categories);
            itemsCategories.Single(x => x.Text == ad.Category.Name).Selected = true;

            List<SelectListItem> itemsCities = DropDownCitiesMenu(cities);
            itemsCities.Single(x => x.Text == ad.City.Name).Selected = true; ;

            ViewBag.AdCategory = itemsCategories;
            ViewBag.AdCity = itemsCities;
            


            return View(new EditViewModel()
            {
                Id = ad.Id,
                Name = ad.Name,
                ImageUrl = ad.ImageUrl,
                PhoneNumber = ad.PhoneNumber,
                Price = ad.Price,
                Description = ad.Description,

            });
        }

        [HttpPost]
        public IActionResult Create(CreateAdViewModel model)
        {
            var user = userManager.GetUserAsync(User).Result;
            var (created, error) = adService.Create(model, user);
            if (!created)
            {
                ModelState.AddModelError("",error);
                return View();
                //return Redirect("/Ad/Create");
            }

            return Redirect("/");
        }

        [HttpPost]
        public IActionResult Edit(EditViewModel model)
        {
            adService.Edit(model);
            
            return Redirect($"/Ad/Details/{model.Id}");

        }

        public IActionResult Delete(string id)
        {
            var removed = adService.Delete(id);
            if (!removed)
            {
                return Redirect($"/Ad/Details/{id}");
            }
            return Redirect("/");
        }


        private static List<SelectListItem> DropDownCategoriesMenu(IOrderedQueryable<Category> categories)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var category in categories)
            {
                items.Add(new SelectListItem { Text = category.Name });
            }

            return items;
        }
        private static List<SelectListItem> DropDownCitiesMenu(IOrderedQueryable<City> cities)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var city in cities)
            {
                items.Add(new SelectListItem { Text = city.Name });
            }

            return items;
        }

    }
}

MarketArea/MarketArea/Controllers/CommentController.cs
using MarketArea.Contracts;
using MarketArea.Data.Common;
using MarketArea.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MarketArea.Controllers
{
    public class CommentController : BaseController
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly ICommentService commentService;
        public CommentController(UserManager<IdentityUser> _userManager, ICommentService _commentService)
        {
            userManager = _userManager;
            commentService = _commentService;
        }

        [HttpPost]
        public IActionResult Add(string id, string text)
        {
            var user = userManager.GetUserAsync(User).Result;
            commentService.Add(id, text, user);

            return Json(new { result = "success" });
        }

        public IActionResult Remove(Dictionary<string,string> ids)
        {
            var adId = ids.Values.First();
            var commnetId = ids.Values.Last();
            commentService.Remove(commnetId);

             return Redirect($"/Ad/Details/{adId}");
        }

    }
}

MarketArea/MarketArea/Views/Ad/All.cshtml
@model FavouritesViewModel
<section class="mainpage-gallery" id="mainpageAds"></section>
<head>
    <title>@Model.CurrentCategory</title>
</head>

<div class="gallerywide" id="gallerywide">

    @foreach (var fav in Model.FavouriteAds)
    {
        <div class="wrapper">
            <div class="thumbnail">
                <div class="cb">
                    <label>
                        @if (fav.IsChecked)
                        {
                            <input class="favoriteCheck" type="checkbox" id="@fav.Ad.Id" checked>
                        }
                        else
                        {
                            <input class="favoriteCheck" type="checkbox" id="@fav.Ad.Id">
                        }
                        <i class="fas fa-heart"></i>
                        <span>Favorite</span>
                    </label>
                </div>
                <img class="img" src="@fav.Ad.ImageUrl" alt="">
                <div class="caption">
                    <h6 class="normal">
                        <a asp-controller="Ad" asp-action="Details" asp-route-id="@fav.Ad.Id" title="@fav.Ad.Name">
                            <strong>@fav.Ad.Name</strong>
                        </a>
                    </h6>

                    <ul class="date-location">
                        <li>@fav.Ad.City.Name</li>
                        <li>@fav.Ad.DateFrom</li>
                    </ul>
                    <h6 class="pull-right">@fav.Ad.Price.ToString("c2",CultureInfo.CreateSpecificCulture("bg-BG"))</h6>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts{
<script src="~/js/favoriteCheck.js" asp-append-version="true"></script>
}

MarketArea/MarketArea/Views/Ad/Create.cshtml
@model CreateAdViewModel
@{
    ViewData["Title"] = "Create a new ad";
}
<div class="text-center">
    <h1><u>@ViewData["Title"]</u></h1>
    <form method="post">
        <label for="name">Category</label>
        <div class="form-group">
            @Html.DropDownList("AdCategory")
        </div>
        <label for="name">City</label>
        <div class="form-group">
            @Html.DropDownList("AdCity")
        </div>
        <div class="form-group">
            <label for="name">Title</label>
            <input type="text" class="form-control" id="name" name="Name" placeholder="Title">
        </div>
        <div class="form-group">
            <label for="price">Price</label>
            <input type="text" class="form-control" id="price" name="Price" placeholder="0.00">
        </div>
        <div class="form-group">
            <label for="phoneNumber">Phone Number</label>
            <input type="text" class="form-control" id="phoneNumber" name="PhoneNumber" placeholder="+359...">
        </div>
        <div class="form-group">
            <label for="imageUrl">Image</label>
            <input type="text" class="form-control" id="ImageUrl" name="ImageUrl" placeholder="https://...">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" id="description" name="Description" placeholder="Text...">
        </div>
        <button type="submit" class="btn btn-primary text-uppercase">Submit</button>
    </form>
</div>

MarketArea/MarketArea/Views/Ad/Details.cshtml
@inject UserManager<IdentityUser> userManager
@model LikeAdViewModel

<h2 class="text-center"><u>@Model.Ad.Name</u></h2>

<div class="detailPage">

    <div class="counter">
        <p><i class="fas fa-eye"></i> Seen: @Model.NumberOfSeen</p>
    </div>
    <img alt="@Model.Ad.Name" src="@Model.Ad.ImageUrl">

    <div class="caption-full">
        <h3 class="detailPrice">@Model.Ad.Price.ToString("c2",CultureInfo.CreateSpecificCulture("bg-BG"))</h3>
        <dl>
            <dt>Contact us:</dt>
            <dd><u>Phone:</u> @Model.Ad.PhoneNumber</dd>
            <dd><u>Email:</u> @Model.Ad.Email</dd>
            <dd><u>City:</u> @Model.Ad.City.Name</dd>
        </dl>
        <p><u>Info:</u> @Model.Ad.Description</p>
        <ul>
            <li>Valid until: @Model.Ad.DateTo.ToString("d")</li>
        </ul>
        <div class="LikeBtn">
            <button class="Like" id="@Model.Ad.Id">
                <i class="far fa-thumbs-up"></i>Likes @Model.NumberOfLikes
            </button>
        </div>

        @if (@Model.Ad.UserId == userManager.GetUserId(User))
        {
            <span class="EditBtn">
                <button class="button">
                    <a class="btn btn-edit" asp-controller="Ad" asp-action="Edit"
                   asp-route-id="@Model.Ad.Id">Edit</a>
                </button>
            </span>
        }
        @if (@Model.Ad.UserId == userManager.GetUserId(User) || User.IsInRole("Administrator"))
        {
            <span class="DeleteBtn">
                <button class="button">
                    <a class="btn btn-delete" asp-controller="Ad" asp-action="Delete"
                   asp-route-id="@Model.Ad.Id">Delete</a>
                </button>
            </span>
        }
    </div>

    <form method="post">
        <div class="cmt">
            <div class="form-outline">
                <label for="addComment">Add a comment:</label>
                <textarea class="form-control" id="textAreaExample" rows="4" placeholder="What is your comment for this ad?"></textarea>
            </div>
            <div class="justify-content-between mt-3">
                <button type="button" id="btnSend" name="@Model.Ad.Id" class="btn btn-success">Send</button>
            </div>
        </div>
    </form>
    <hr>

    @if (@Model.Comments != null)
    {
        <div id="ListOfComments">

            @foreach (var cmt in Model.Comments)
            {
                <div class="d-flex flex-start" id="@cmt.Id" style="width:400px;">
                    <div>
                        <h6 class="fw-bold mb-1">@cmt.User.UserName</h6>
                        <div class="d-flex align-items-center mb-3">
                            <p class="mb-0">@cmt.DateFrom.ToString("d")</p>
                        </div>
                        <p class="mb-0">
                            @cmt.Text
                        </p>
                    </div>
                    @if (@cmt.UserId == userManager.GetUserId(User) || User.IsInRole("Administrator"))
                    {
                        var parms = new Dictionary<string, string>
            {
            {"adId", @Model.Ad.Id},
            {"commentId", @cmt.Id}
            };
                        <span class="RemoveBtn">
                            <button class="button">
                                <a class="btn btn-remove" asp-controller="Comment" asp-action="Remove" asp-all-route-data="parms">Remove</a>
                            </button>
                        </span>
                    }
                </div>
                <hr>
            }
        </div>
    }
</div>



@section Scripts{
<script src="~/js/likeButton.js" asp-append-version="true"></script>
<script src="~/js/comment.js" asp-append-version="true"></script>
@*<script src="~/js/listOfComments.js" asp-append-version="true"></script>*@
}

MarketArea/MarketArea/Views/Ad/Edit.cshtml
@model EditViewModel
@{
    ViewData["Title"] = "Edit your Ad";
}
<div class="text-center">
    <h1>@ViewData["Title"]</h1>


    <form method="post">
        <input type="hidden" name="Id" value="@Model.Id" />
        <label for="name">Category</label>
        <div class="form-group">
           @Html.DropDownList("AdCategory")
        </div>
        <label for="name">City</label>
        <div class="form-group">
            @Html.DropDownList("AdCity") 
        </div>
        <div class="form-group">
            <label for="name">Title</label>
            <input type="text" class="form-control" id="name" placeholder="Title" asp-for=@Model.Name>
        </div>
        <div class="form-group">
            <label for="price">Price</label>
            <input type="text" class="form-control" id="price" placeholder="0.00" asp-for=@Model.Price>
        </div>
        <div class="form-group">
            <label for="phoneNumber">Phone Number</label>
            <input type="text" class="form-control" id="phoneNumber" placeholder="+359..." asp-for=@Model.PhoneNumber>
        </div>
        <div class="form-group">
            <label for="imgUrl">Image</label>
            <input type="text" class="form-control" id="imgUrl" placeholder="https://..." asp-for=@Model.ImageUrl>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" id="description" placeholder="Text..." asp-for=@Model.Description>
        </div>
        <button type="submit" class="btn btn-primary text-uppercase">Save</button>
    </form>
</div>